../../rtl/delta/delta_ctrl/delta_ctrl.v
../../rtl/delta/delta_ctrl/linear_interpolation.v
../../rtl/delta/delta_ctrl/top_delta_ctrl.v
../../rtl/delta/motion_ctrl/stepper_motor_ctrl.v
../../rtl/delta/motion_solver/calculate_angle.v
../../rtl/delta/motion_solver/cordic_serial.v
generated/ip_multiplier/ip_multiplier.v
generated/ip_multiplier/rtl/ipml_mult_v1_3_ip_multiplier.v
../../rtl/delta/motion_solver/motion_solver.v
../../rtl/delta/motion_solver/pretreat_data.v
../../rtl/delta/motion_solver/sqrt.v
../../rtl/delta/transmission_tape/tran_tape.v
../../rtl/delta/motion_ctrl/stepper_motor_reset.v
../../rtl/linkage_arm/motion_ctrl/stepper_motor_ctrl_1.v
../../rtl/linkage_arm/motion_ctrl/stepper_motor_ctrl_2.v
../../rtl/linkage_arm/motion_ctrl/stepper_motor_ctrl_3.v
../../rtl/linkage_arm/motion_ctrl/stepper_motor_ctrl_4.v
../../rtl/linkage_arm/motion_solver/arm_motion_solver.v
../../rtl/linkage_arm/motion_solver/divider.v
../../rtl/linkage_arm/motion_solver/signed_divider.v
../../rtl/linkage_arm/motion_solver/solver_big_and_small_arm.v
../../rtl/linkage_arm/motion_solver/solver_rotation.v
../../rtl/linkage_arm/ram_ctrl/ram_ctrl_inst.v
../../rtl/linkage_arm/motion_solver/sqrt_32.v
../../rtl/linkage_arm/motion_solver/cordic_serial_32.v
../../rtl/delta/uart/uart_tx.v
../../rtl/delta/uart/RFID_uart.v
../../rtl/delta/uart/uart_rx.v
../../rtl/delta/uart/camera_uart_top.v
source/uart/uart_rx_top.v
source/uart/win_tx_top.v
